// Generates backend/supabase/seed.sql from the categories.md snapshot.
// Run from backend/:  pnpm exec tsx supabase/seed/build-seed.ts
//
// categories.md is the human-readable source of truth (a snapshot of the live
// catalog). This emits idempotent upserts so `supabase db reset` loads the full
// catalog on top of the migration-seeded subset.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const mdPath = join(here, 'categories.md');
const outPath = join(here, '..', 'seed.sql');

interface Row { major: string; sub: string | null; order: number }

const rows: Row[] = [];
let inTable = false;
for (const raw of readFileSync(mdPath, 'utf8').split('\n')) {
  const line = raw.trim();
  if (line.startsWith('<!--') || line.startsWith('-->')) continue;
  if (/^Major\s*\|\s*Sub\s*\|\s*Order/i.test(line)) { inTable = true; continue; }
  if (!inTable || !line.includes('|')) continue;
  if (/^[-\s|]+$/.test(line)) continue; // header separator row
  const cells = line.split('|').map((c) => c.trim());
  if (cells.length < 3 || !cells[0]) continue;
  const [major, sub, orderStr] = cells;
  rows.push({
    major,
    sub: sub === '' || sub.toUpperCase() === 'NULL' ? null : sub,
    order: Number.parseInt(orderStr, 10) || 0,
  });
}

if (rows.length === 0) throw new Error('build-seed: no category rows parsed from categories.md');

const esc = (s: string) => s.replace(/'/g, "''");
const values = rows
  .map((r) => `  ('${esc(r.major)}', ${r.sub === null ? 'NULL' : `'${esc(r.sub)}'`}, ${r.order})`)
  .join(',\n');

const sql = `-- Generated by supabase/seed/build-seed.ts from seed/categories.md — DO NOT EDIT BY HAND.
-- Full live-catalog snapshot (${rows.length} rows). Upserts over the migration-seeded subset
-- so the local DB matches the production catalog (the SSOT).
INSERT INTO categories (major, subcategory, sort_order) VALUES
${values}
ON CONFLICT ON CONSTRAINT uq_category DO UPDATE SET sort_order = EXCLUDED.sort_order;
`;

writeFileSync(outPath, sql);
console.log(`build-seed: wrote ${outPath} with ${rows.length} category rows.`);
